name: Mirroring

on:
  workflow_dispatch:

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:                                              # <-- must use actions/checkout before mirroring!
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            org-85143255@github.com:kyanny-corp-enterprise-cloud-testing/zd-2857436-target.git
          ssh_private_key:                              # <-- use 'secrets' to pass credential information.
            ${{ secrets.SSH_PRIVATE_KEY }}
